
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 08:36:33 COT 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIES = 6;
  public static final int EOF = 0;
  public static final int CONVERTIR = 7;
  public static final int NUMERO = 8;
  public static final int PULGADAS = 5;
  public static final int METRO = 3;
  public static final int SALTO = 2;
  public static final int error = 1;
  public static final int CENTIMETRO = 4;
}

